### ISSUE TITLE
V0.2.12 Bug mit Statusinformationen 

### ISSUE THREAD

**Issue by Gurke258** [ioBroker/ioBroker.vis-2-widgets-material#114]
Ich habe immer wieder das Problem das sich das Widget Statusinformationen in das Feld HTML Vorlage verwandelt.
![grafik](https://user-images.githubusercontent.com/36326543/226414480-b8b8a51e-8ed0-4919-9077-7889141f2b9d.png)

**Comment by Feuer-sturm** [comment]
Material-Widgets v0.2.13

@Gurke258 Ich hätte gesagt, dass der Name gewollt ist.
Hast du einen Screenshot das bei dir auch mal "Statusinformationen" steht?
Rechts im Menü taucht auch der Name "HMTL-Vorlage" auf
![grafik](https://user-images.githubusercontent.com/25422320/230767614-ca18e77c-6895-431b-a80f-9deeeb50b5fa.png)

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren (vis-2)
