### ISSUE TITLE
JSON Chart like vis-materialdesign

### ISSUE THREAD

**Issue by LembkeM** [ioBroker/ioBroker.vis-2-widgets-material#163]
Hi,
i love VIS 2 and i would like to create some Graphs.
Is there a way like in vis-materialdesign to create it like the Json Chart

Or is there a plan for that feature?

Best regards
Markus

**Comment by GermanBluefox** [comment]
Can you give some screenshots of what you want?

**Comment by Morluktom** [comment]
With eChart you can do a JSON Chart.

**Comment by GermanBluefox** [comment]
Unclear requests
