### ISSUE TITLE
Erweiterte Optionen im Schalter Widget 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.vis-2-widgets-material#173]
Es wäre klasse, über das Schalter Widget auch die erweiterten Eigenschaften einer Lampe aufrufen zu können.

Dass wenn ich zB dort drücke
![Screenshot_20230912_064226_ioBroker Visu](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/7cec16ae-34d1-49f9-a2e6-8a95cdfd2d6d)
Dieser Dialog aufgeht:
![Screenshot_20230912_064154_ioBroker Visu](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/ddfd10f0-6ab5-4e73-ae69-217938467657)

Quasi eine Vermischung von Schalter und rgb Licht widget.
Aktuell wird es bei mehreren rgb Lampen sehr unübersichtlich, da das widget recht groß ist. 

Hier ist es finde ganz schön umgesetzt (lovelace):
![Screen_Recordin-1694494707531](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/138a0c71-970a-41fa-abb8-191ee58fea67)

**Comment by GermanBluefox** [comment]
Es gibt jetzt RGB type (from 1.2.0)

![Animation](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/4582016/5460574d-a791-4554-93c3-b2e0d2449c31)

**Comment by Feuer-sturm** [comment]
@ipod86 bitte einmal mit der aktuellen Version nachtesten.

**Comment by ipod86** [comment]
Sieht gut aus.
Hab aber zum testen keine rgb Leuchtmittel. Nur Farbtemperatur (da hab ich ja auch noch ein issue zu offen).

![Screenshot_20231008_213828_ioBroker Visu](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/972ba964-94c6-4e12-ae75-d8336dc94d63)

**Comment by Feuer-sturm** [comment]
Dann mache ich erstmal hier zu :-)
