### ISSUE TITLE
Darstellung Wetter Widget 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.vis-2-widgets-material#175]
Ich finde für deutsche Systeme die Abkürzungen der Wochentage unglücklich. Mo, Di, Mi etc mit 2 Stellen wären wesentlich sinnvoller.

![Screenshot_20230917_084118_ioBroker Visu](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/a2de5bf1-27a2-4483-a4ba-57898c73ee12)

Die Detailansicht ist bei kleinen Bildschirmen ist ziemlich zerschossen.
![Screenshot_20230917_084145_ioBroker Visu](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/5ff2cd6f-5c7c-4d21-a000-a66508bacdaf)

**Comment by ammawel** [comment]
@ipod86 
Wo gibt es denn bei den vis-2-material-widgets das Wetter-Widget?

**Comment by ipod86** [comment]
Garnicht, ich hab hier falsch geschrieben.....
Oh man, mal schauen ob ich das hier löschen kann.....

**Comment by Feuer-sturm** [comment]
@ipod86 Bitte dieses issue schließen, du hast ja schon im passenden repository ein neues erstellt.
