### ISSUE TITLE
Responsive-Einstellung Reihenlücke / vertikaler Abstand nur im Edit-Mode

### ISSUE THREAD

**Issue by ammawel** [ioBroker/ioBroker.vis-2-widgets-material#176]
Der vertikale Abstand (Reihenlücke) der Responsive-Einstellungen wird nur im Edit-Mode eingehalten. Wechselt man in den View-Mode oder in die Runtime-Darstellung wird der Abstand nicht übernommen. Es handelt sich um den unteren Abstand des jeweiligen Widgets. Bei anderen Widget-Pakecten (z.B. Basic) taucht das Problem nicht auf, vgl. Screenshots mit 40px Reihenlücke.

**Edit-mode**
![edit-mode](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/51128844/6d1217e2-771a-4ccd-be03-c6a8cfd061f5)

**View-mode / Runtime**
![view-mode](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/51128844/bfd25cf0-b4e5-4cf1-b38f-961bec26da6f)

**Comment by Feuer-sturm** [comment]
@ammawel Please check with current version

**Comment by ammawel** [comment]
@Feuer-sturm , is fixed
> Fixed in vis 2.3.1
