### ISSUE TITLE
Istwert mit Diagramm funktioniert nicht bei SQL 

### ISSUE THREAD

**Issue by Morluktom** [ioBroker/ioBroker.vis-2-widgets-material#177]
Es wird kein Diagramm angezeigt bei dem Widget "Istwert mit Diagramm" in Verbindung mit dem SQL Adapter.

**Comment by intruder7777** [comment]
auch in Verbindung mit influx nicht

**Comment by Feuer-sturm** [comment]
@intruder7777 Bei mir wird das Widget mit einem Diagramm gefüllt. Der Datenpunkt wird über influx historisiert.
SQL Datenbank hab ich nicht im Einsatz

![grafik](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/25422320/480dab68-6243-4df6-b99a-a2218d40da0c)

material-widgets v1.2.1
vis-2 version 2.3.0

**Comment by Morluktom** [comment]
@Feuer-sturm:
Vis 2 Widgets Material: 1.3.1
Vis 2: 2.3.2
SQL: 2.2.0

**Comment by Feuer-sturm** [comment]
@Morluktom gibt es Fehler in der Browser Konsole?

**Comment by Morluktom** [comment]
Ja da habe ich eine Menge drin stehen:

`[Log] iobroker.vis-2@2.3.2 using theme "light" (836.1acee0c9.chunk.js, line 1)
[Log]  (main.42899aa0.js, line 2)
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

[Log] Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters (main.42899aa0.js, line 2)
[Log] Help us to create open source project with reactJS! (main.42899aa0.js, line 2)
[Log] See you :) (main.42899aa0.js, line 2)
[Log] [2023-10-15T14:29:03.021Z] Try to connect (socket.io.js, line 83)
[Log] Skip script "basic" widgets/basic/js/table.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "basic" inline (489.863d9b5c.chunk.js, line 2, x41)
[Log] Skip script "echarts" inline (489.863d9b5c.chunk.js, line 2, x2)
[Log] Skip script "info" ../adapter/info/lib/js/commons.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "info" ../adapter/info/lib/js/popupnews.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "info" widgets/info/js/info.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "info" inline (489.863d9b5c.chunk.js, line 2, x2)
[Log] Skip script "jqplot" widgets/jqplot/js/jquery.jqplot.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "jqplot" inline (489.863d9b5c.chunk.js, line 2, x2)
[Log] Skip script "jqui-mfd" inline (489.863d9b5c.chunk.js, line 2, x28)
[Log] Skip script "jqui" lib/js/jquery-ui-timepicker-addon-1.6.3.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "jqui" inline (489.863d9b5c.chunk.js, line 2, x13)
[Log] Skip script "lg-ess-home" widgets/lg-ess-home/js/lg-ess-home.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "lg-ess-home" widgets/lg-ess-home/lib/echarts.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "lg-ess-home" widgets/lg-ess-home/js/chart.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "lg-ess-home" inline (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib/raw/moment-with-locales.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib/raw/round-slider.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib/raw/sentry/bundle.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib/raw/sentry/captureconsole.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/lib/raw/sentry/dedupe.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/js/materialdesign.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" widgets/materialdesign/js/widgets.min.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "materialdesign" inline (489.863d9b5c.chunk.js, line 2, x46)
[Log] Skip script "metro" widgets/metro/js/metro.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "metro" inline (489.863d9b5c.chunk.js, line 2, x29)
[Log] Skip script "swipe" inline (489.863d9b5c.chunk.js, line 2, x3)
[Log] Skip script "tabs" inline (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/OnOffScheduleWidget.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/TriggerWithAction.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/TimeTrigger.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/AstroTrigger.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/Weekdays.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/OnOffStateAction.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/ConditionAction.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" widgets/time-switch/js/time-switch.js (489.863d9b5c.chunk.js, line 2)
[Log] Skip script "time-switch" inline (489.863d9b5c.chunk.js, line 2)
[Warning] common.visWidgets.i18n is deprecated. Use common.visWidgets.vis2energyWidgets.i18n instead. (489.863d9b5c.chunk.js, line 2)
[Warning] common.visWidgets.i18n is deprecated. Use common.visWidgets.vis2gaugeWidgets.i18n instead. (489.863d9b5c.chunk.js, line 2)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_translations_js.395fc3f6.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_translations_js.10c291be.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_translations_js.cace16e5.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_translations_js.8cc6492a.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Switches_jsx-src_sketch_css.e2297072.chunk.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Generic_jsx-src_ObjectChart_jsx.b796934b.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Thermostat_jsx.9fe80f2d.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Components_BlindsBase_js.a97ca885.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Actual_jsx-node_modules_babel_runtime_helpers_esm_setPrototypeOf_js.9187ac06.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Components_DoorAnimation_js-src_Components_LockAnimation_js.05f2a81b.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Switches_jsx-src_sketch_css.a3283c56.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Vacuum_jsx.f71da19d.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_sketch_css-node_modules_babel_runtime_helpers_esm_asyncToGenerator_js-node_modules_babel_-720972.e2297072.chunk.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Blinds_jsx-src_Generic_jsx.8b34b70b.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_RGBLight_jsx-node_modules_babel_runtime_helpers_esm_assertThisInitialized_js-node_modules-5100e3.c9f9cbf4.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Map_jsx-node_modules_leaflet_dist_leaflet_css-node_modules_babel_runtime_helpers_esm_obje-1f1968.c7bfc0ae.chunk.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Clock_jsx.583011a2.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Lock_jsx.1d0f23c9.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_SimpleState_jsx.ecde697f.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_ThemeSwitcher_jsx.0be7c126.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Player_jsx.d3deecb7.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_ViewInWidget_jsx.150def21.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Security_jsx.926af91a.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Camera_jsx.6117a8af.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Html_jsx.bf234410.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Generic_jsx-node_modules_react_jsx-runtime_js.423437a8.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_WasherDryer_jsx.19b9072c.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_deviceWidget_js.5b77c3f1.chunk.js.map, line 0)
[Log] Translate: jqui_Close (489.863d9b5c.chunk.js, line 2)
[Log] Translate: jqui_input (489.863d9b5c.chunk.js, line 2)
[Log] Translate: jqui_off (489.863d9b5c.chunk.js, line 2)
[Log] Translate: jqui_on (489.863d9b5c.chunk.js, line 2)
[Log] Translate: Value (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplHtml because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplShapes because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplIFrame because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplImage because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplLink because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplFrame because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplStatefulIFrame8 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplStatefulContainerView8 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplStatefulImage8 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplHtmlNav because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplFilterDropdown because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueFloat because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueStringRaw because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueStringImg because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplTimeValue because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueTimestampValue because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueTimestamp because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueLastchange because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueList because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueListHtml because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueListHtml8 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplAckBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueBoolCheckbox because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueInput because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueBoolSelect because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueBoolCtrl because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueBoolCtrlSvg because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplBasicState because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplRedNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplBulbOnOffCtrl because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueFloatBar because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplNote because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplTableBody because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplHtmlLogout because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplValueGesture because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplSpeech2Text because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplFullScreen because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored basic/tplScreenResolution because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored echarts/tplEchartsChart because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored info/tplInfoMessages because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored info/tplInfoCalendar because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqplot/tplJqplotGauge because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdLight because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdLightCtrl because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdLightOnOffDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdLightDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdSocket because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdSocketCtrl because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdShutter because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdShutterDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdBlind because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdBlindDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdHeating because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdWindow because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdWindowBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdRoofWindowBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdDoor because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdGarage because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdValve because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdValveDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCustom10 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCustom10Dialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCamSnapshot because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplValMfdCamSnapshot because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCamMjpg because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplValMfdCamMjpg because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCamVideo because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplValMfdCamVideo because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui-mfd/tplMfdCamVideoObject because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiToogle because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiInputDate because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiInputDatetime because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiInputSet because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiRadio because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiRadioList because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiSelectList because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplJquiRadioSteps because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplIconStateBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplIconStatePushButton because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored jqui/tplIconInc because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored lg-ess-home/tplLgEssHomeChart because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-value because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Navigation-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Link-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-State-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-State-Multi-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Adition-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Toggle-vertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Navigation because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Link because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-State because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-State-Multi because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Adition because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Button-Toggle because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-Navigation because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-Link because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-State because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-State-Multi because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-Adition because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-Button-Toggle because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Input because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Autocomplete because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Select because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Switch because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-CheckBox because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Vuetify-Slider because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Slider-Round because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Progress because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Progress-Circular because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Card because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-TopAppBar-Navigation because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-List because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon-List because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Chart-Bar because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Chart-Line-History because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Chart-JSON because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Chart-Pie because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-ColorScheme-Preview because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Vuetify-Dialog-View because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Vuetify-Dialog-iFrame because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Table because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Masonry-Views because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Grid-Views because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Alerts because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Calendar because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Icon because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored materialdesign/tplVis-materialdesign-Installed-Version because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroSlider because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroSliderVertical because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroValueBoolCheckbox because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroValueBoolSwitch because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileNav because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileString because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileBool because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileBoolDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileList8 because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileBoolNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileState because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileToggle because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileStateNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDimmer because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDimmerDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileShutter because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileShutterDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileHeating because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileHeatingDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDialogStatic because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileStaticDialogNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDialogString because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileStringDialogNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDialog because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDialogNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileFrameDialogNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileToggleNumber because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored metro/tplMetroTileDimmerDialogactiv because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored swipe/tplSwipe because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored swipe/tplCarousel because not used in project (489.863d9b5c.chunk.js, line 2)
[Log] Ignored time-switch/tplTime-switchDevicePlan because not used in project (489.863d9b5c.chunk.js, line 2)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_ConsumptionComparison_jsx-node_modules_babel_runtime_helpers_esm_assertThisInitialized_js-a3b647.66c3cb16.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_IntervalSelector_jsx.67538440.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Wizard_jsx.a824b7b9.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_WaterGauge_jsx.55c65fc6.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Consumption_jsx-node_modules_babel_runtime_helpers_esm_assertThisInitialized_js-node_modu-9f7f55.b696c76c.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Distribution_jsx.539cb070.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_ColorGauge_jsx-node_modules_babel_runtime_helpers_esm_defineProperty_js-node_modules_babe-17d7ec.7cfe7aba.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_BatteryGauge_jsx.9a9b6397.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_react-weather_Weather_js-webpack_sharing_consume_default_iobroker_vis-2-widgets-react-dev-fe17a4.08a2daf7.chunk.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_react-weather_Weather_js-webpack_sharing_consume_default_iobroker_vis-2-widgets-react-dev-fe17a4.83721eea.chunk.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (src_Weather_jsx-node_modules_babel_runtime_helpers_esm_objectSpread2_js-node_modules_babel_ru-577953.c93194ca.chunk.js.map, line 0)
[Warning] Common user CSS not found: Not exists (489.863d9b5c.chunk.js, line 2)`

**Comment by intruder7777** [comment]
geht mit influx

**Comment by intruder7777** [comment]
@Feuer-sturm  oder @GermanBluefox  kann es sein dass bei Influx andere Instanzen als die Instanz 0 nicht gehen? Hab bisher immer Werte aus der Instanz 0 angezeigt. Jetzt hab ich einen Datenpunkt der Influx.2 nutzt. Bei dem werden keine Daten angezeigt. Egal was ich mache

**Comment by GermanBluefox** [comment]
> @Feuer-sturm oder @GermanBluefox kann es sein dass bei Influx andere Instanzen als die Instanz 0 nicht gehen? Hab bisher immer Werte aus der Instanz 0 angezeigt. Jetzt hab ich einen Datenpunkt der Influx.2 nutzt. Bei dem werden keine Daten angezeigt. Egal was ich mache

Was ist als "Default history" eingestellt?
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/4582016/45c061b3-6818-45f1-b44d-1ff2f4c977b2)

**Comment by Morluktom** [comment]
Danke, das war bei mir der richtige Tip.
Habe den Default richtig eingestellt jetzt geht es.
