### ISSUE TITLE
Fehler Heizung in "Schalter" Widget 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.vis-2-widgets-material#178]
Ich habe mehrere Fehler in der implimentierung der Heizung in das Schalter Widget.

1. Wenn ich die Temperatur auf der geraden Linie verschiebe (nicht im Popup), "wandert" der Wert gemächlich zum zielwert. Die Zwischenergebnisse werden auch alle zur Heizung übertragen. Wenn ich direkt irgendwo auf die Linie drücke klappt es sofort.
2. Wenn ich die Ansicht zu dem rundem Schieber erweitere, werden Werte die ich über das schieben des Reglers einstelle nicht übernommen bzw an die Heizung gesendet. Drücke ich direkt irgendwo hin klappt es.

Ich kann beides am Smartphone und PC mit der Maus reproduzieren. 

Wie es sich im richtigen Heizungswidget verhält, kann ich nicht sagen. Dieses klappt bei mir (obwohl es wohl gefixt ist) noch immer nicht. 

Material Widgets Vis 2 in 1.2.1 installiert, Vis-2 in 2.2.7

![Screen_Recordin-1695358992552](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/66136363/eee86174-60ef-4d53-80c8-5d398e8e8016)

**Comment by GermanBluefox** [comment]
Bitte Steuerverzögerung benutzen
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/4582016/aa85b83e-fe32-47e8-a80a-0b943eed07f0)

**Comment by ipod86** [comment]
Okay, das macht Sinn.
Das schieben klappt jetzt besser.

Allerdings werden Werte die ich über den runden Schieber einstelle, indem ich den Wert verschiebe, nach wie vor nicht übernommen. Wenn ich nur auf einen Bericht drücke geht es. Beim geraden Schieber klappt das einstellen mit dem wischen.

**Comment by GermanBluefox** [comment]
> Okay, das macht Sinn. Das schieben klappt jetzt besser.
> 
> Allerdings werden Werte die ich über den runden Schieber einstelle, indem ich den Wert verschiebe, nach wie vor nicht übernommen. Wenn ich nur auf einen Bericht drücke geht es. Beim geraden Schieber klappt das einstellen mit dem wischen.
> 
> P. S. Das normale Heizungswidget klappt bei mir nach wie vor nicht.

![Animation](https://github.com/ioBroker/ioBroker.vis-2-widgets-material/assets/4582016/b6dc271e-d006-408a-bbd4-534d54feecfa)
Ich kann das Problem mit dem Runden Schieber nicht nachvorstellen.

**Comment by Feuer-sturm** [comment]
@ipod86 ist das Problem mit den runden Schieber bei dir noch aktuell oder funktioniert es?
