### ISSUE TITLE
up from 0.2.0 widgets folder is missing in npm package

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.vis-2-widgets-material#98]
with 0.1.5 the widgets folder is in the packet in 0.2.0 and 0.2.1 it is missing

**Comment by GermanBluefox** [comment]
Yes, I know, and just now I am trying to find out, why...

**Comment by hombach** [comment]
Should this probably be src-widgets/?

`"main": "main.js",
  "files": [
    "admin/",
    "img/",
    "io-package.json",
    "LICENSE",
    "widgets/"
  ],`

**Comment by hombach** [comment]
Same result still in 0.5.3 ....

**Comment by GermanBluefox** [comment]
Can you re-test? With vis-2 (not vis-2-beta)

**Comment by hombach** [comment]
From my point of view no problems anymore - issue could be closed.
